### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by timbell** [eyolas/ng2-intl#1]
Do you have any usage instructions? I've managed to define a `system.config.js` that gets `ng2-intl` loaded but I've experienced some problems so I could be going about this the wrong way. I'm starting with `ng-intl/dist/index.js`.

Problem 1: the `en.js` in the dist folder is in `es6` so I get a `traceur 404` error. I can get around this by overwriting with the `en.js` from `locale-data`.

Problem 2: I get `"no provider for"` errors for `IntlService` and `IntlLoader`. I'm just importing `FormatService` for now while I'm trying to get the loading right. I can work around this by adding `IntlService` and `IntlLoader` to the providers list in the transcoded `@NgModule` definition in `intl.module.js`.

These are the relevant parts of my system.config.js:

```
map: {
...
      "ng2-intl": "npm:ng2-intl/dist",
...
},
packages: {
...
      "ng2-intl": {
        main: "./index.js",
        defaultExtension: 'js',
        map: {
          "./components": "./components/index.js",
          "./pipes": "./pipes/index.js",
          "./services": "./services/index.js"
        }
      },
      "intl-format-cache": {
        main: "./index.js",
        defaultExtension: 'js'
      },
      "intl-messageformat": {
        main: "./index.js",
        defaultExtension: 'js'
      },
      "intl-messageformat-parser": {
        main: "./index.js",
        defaultExtension: 'js'
      },
      "intl-relativeformat": {
        main: "./index.js",
        defaultExtension: 'js'
      }
...
}
```

**Comment by timbell** [comment]
Problem 2 is fixed - I followed the setup for [ng2-translate](https://github.com/ocombe/ng2-translate) which looks similar

**Comment by eyolas** [comment]
I pushed a version with an umd package. Tell me if the bundle solved you problem :)

**Comment by timbell** [comment]
Thanks - that fixes it. 
The `intl-` libs aren't bundled - is that intentional?

**Comment by timbell** [comment]
Hey, you bundled them - thanks!
Are you looking at compatibility with `ahead-of-time` compilation (ngc) ?

**Comment by eyolas** [comment]
Yes i bundled them :)

My priority is writing the documentation and tests. After i'm looking at compatibility with ahead-of-time compilation (ngc).
