### ISSUE TITLE
processMessageFormat not distinguishing between undefined/null and empty string

### ISSUE THREAD

**Issue by timbell** [eyolas/ng2-intl#2]
I have this message: `{count, selectordinal, =0 {} other {(#)}}` to display nothing if count is zero or the count in brackets otherwise. Unfortunately I currently get the unprocessed message returned when count = 0 as `processMessageFormat` doesn't distinguish between an empty string and undefined/null when testing the formatted and default messages.

Replacing tests such as `if (!formattedMessage && defaultMessage)` by something like `if (typeof formattedMessage !== "string" && typeof defaultMessage === "string")` would fix it I think.

**Comment by eyolas** [comment]
It is a bug of intl-messageformat

**Comment by timbell** [comment]
That's not my understanding. intl-messageformat will always return a string (or throw an exception). My point is that an empty string should be treated as a valid formatted message. Currently the `if (!formattedMessage...` tests prevent this. I made the following changes locally to make it work how I think it should:

From here: [`if (!formattedMessage...`](https://github.com/eyolas/ng2-intl/blob/10b943770a91ca9dfafde7ba2ec780acf6c91443/module/src/services/format.service.ts#L230)

```
    if (typeof formattedMessage !== 'string' && defaultMessage) {
      try {
        let formatter = formatters.getMessageFormat(
          defaultMessage, defaultLocale, formats
        );

        formattedMessage = formatter.format(values);
      } catch (e) {
        debug(
          `[Ng2 Intl] Error formatting the default message for: "${id}"` +
          `\n${e}`
        );
      }
    }

    if (typeof formattedMessage !== 'string') {
      debug(
        `[Ng2 Intl] Cannot format message: "${id}", ` +
        `using message ${message || defaultMessage ? 'source' : 'id'} as fallback.`
      );
    }

    return typeof formattedMessage === 'string' ? formattedMessage : message || defaultMessage || id;
  }
```

The tests on formattedMessage are basically picking up the case where an empty `message` is passed to processMessageFormat so formattedMessage is never assigned to and remains undefined.

**Comment by timbell** [comment]
Thanks for the fix. 

Unfortunately, I think it's broken the default message handling when values are passed in.

```this.formatService.formatMessage({id: "does_not_exist", defaultMessage: "default_message"});``` 
correctly returns: `"default_message"`

but:
```this.formatService.formatMessage({id: "does_not_exist", defaultMessage: "default_message"}, {foo: "bar");```
now returns: `undefined`

**Comment by timbell** [comment]
Just wanted to check you'd seen my last message about the default message handling problem? Should I submit a  new issue?
